### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by ZhaoChenxi-nku** [leolyliu/TACO-Instructions#2]
请问数据集可以提供一个百度网盘的下载形式吗，谢谢！

**Comment by leolyliu** [comment]
Hi zhaochenxi515,

We are seeking for the storage space of Baidu Netdisk. If we have found enough space, we will synchronize the dataset there :)

**Comment by leolyliu** [comment]
@zhaochenxi515 We have uploaded a [BaiduNetDisk](https://pan.baidu.com/s/1gANrhzdUyvsUGXcDB4xMfQ?pwd=kg7j) version for the pre-released version.
