### ISSUE TITLE
Two trouble shootings

### ISSUE THREAD

**Issue by gemcollector** [leolyliu/TACO-Instructions#3]
```
File "taco/lib/python3.9/site-packages/scipy/interpolate/_fitpack_impl.py", line 103, in <module>
    'iwrk': array([], dfitpack_int), 'u': array([], float),
TypeError
```
method: `pip install scipy==1.10.1`

```
ModuleNotFoundError: No module named 'chumpy'
```
method: `pip3 install git+https://github.com/scottandrews/chumpy.git@fe51783e0364bf1e9b705541e7d77f894dd2b1ac`

**Comment by leolyliu** [comment]
Hi, gemcollector:

Thank you for your reminder. We have updated the ```requirements.txt```.
