### ISSUE TITLE
Release of full hand poses 

### ISSUE THREAD

**Issue by enesduran** [leolyliu/TACO-Instructions#4]
Hello, thank you for your work! 

AFAIK you only have released a subset of the hand poses under the folder TACO_Dataset_Examples. Am I wrong? Are you intending to release whole hand pose data? 

Best

**Comment by leolyliu** [comment]
Hi enesduran,

So far, we have only released a subset of the hand poses under TACO_Dataset_Examples. We expect to release the full dataset in August 2024. Now we are fixing a few errors in object poses, if you need the hand-object poses of the whole dataset urgently, we can provide you with the current version.

Best,
Yun Liu

**Comment by enesduran** [comment]
Hey, thank you for the fast response! I think it is not an urgent matter if full version of the dataset is going to be shared in August. Another question is do you intend to improve the hand annotations in the dataset? The following two examples are the cases where: 1) The hand shapes are visibly different 2) The annotations are jittery does not align well with the video. 
1)
![example_20231005_032](https://github.com/user-attachments/assets/2c0b5c2f-221a-4e83-b19e-fa0b98387471)

2)

https://github.com/user-attachments/assets/d1ea32cb-ca17-4fe2-976f-36b5d97fcb8b

**Comment by leolyliu** [comment]
Hi enesduran,

(1) For the hand shapes, each hand of each person will share the same hand shape among the whole dataset. The shapes of the left hand and the right hand could be different. We will improve some persons' hand shapes in the next dataset version.

(2) The jittering is hard to fix due to heavy occlusions. Currently, we have tried our best to reconstruct hands from the videos. If better annotations are acquired, we will update our dataset.

Best

**Comment by enesduran** [comment]
Hey, so AFAIK the hand shape parameters for each unique hand will be the same across all timesteps. However, the shape parameters do not have to be same for right and left hand. Thanks for your efforts! Looking forward to seeing new version!

**Comment by leolyliu** [comment]
> Hey, so AFAIK the hand shape parameters for each unique hand will be the same across all timesteps. However, the shape parameters do not have to be same for right and left hand. Thanks for your efforts! Looking forward to seeing new version!

Yes, exactly.
