### ISSUE TITLE
CMR Dataloader for DexYCB dataset

### ISSUE THREAD

**Issue by delaprada** [leolyliu/TACO-Instructions#6]
Hi, thanks for this amazing work!

I am interested in your cross-dataset evaluation for TACO and DexYCB. However, I encounter some problems for the DexYCB dataloader and could not reach a satisfying result. May I ask can you share your dataloader for DEX-ycb dataset of CMR method? It is related to the Table. 2 in your paper.

Thank you very much for your assistance!

**Comment by leolyliu** [comment]
Hi delaprada,

We have uploaded our modified codes of CMR and MobRecon, and uploaded examples of the prepared DexYCB and TACO datasets in [TACO Cross Dataset Evaluation](https://cloud.tsinghua.edu.cn/d/8e282615744c4fca8a42/). Our experiment logs and several pre-trained models are included in the codes. We hope they can help.

Best,
Yun

**Comment by delaprada** [comment]
Thank you very much!

**Comment by delaprada** [comment]
Sorry, I still have a question about the images. It seems you are not using the original DexYCB image, but the preprocessed one. May I ask how you preprocess the images? Othervise, using the original image with your provided bbox.json is not compatible with each other.

Thank you very much!

**Comment by leolyliu** [comment]
We use the preprocessed TACO and DexYCB image patches. The data preprocessing codes are ```HandMesh_released/mobrecon/datasets/prepare_bimanual_data.py``` and ```HandMesh_released/mobrecon/datasets/prepare_DexYCB_data.py```.

**Comment by delaprada** [comment]
Thank you for your detailed explanation!
