### ISSUE TITLE
world coordinate system basis vector

### ISSUE THREAD

**Issue by ligengen** [leolyliu/TACO-Instructions#8]
Hi @leolyliu,

Could you please clarify what are the coordinate system axes? I couldn't find them anywhere. Is it x left, y up, z forward? Is it left-handed or right-handed system? Thank you!

**Comment by leolyliu** [comment]
Hi @ligengen,
Which coordinate system do you mention? Is it the world coordinate system or one of the camera coordinate systems?

**Comment by ligengen** [comment]
Hi Leolyliu,

I mainly want to know the detail about world coordinate system. But it
would be the best that you can also detail camera coordinates. Thank you!

**Comment by leolyliu** [comment]
Hi @ligengen ,
We have uploaded the code [visualize_world_coordinate_system.py](https://github.com/leolyliu/TACO-Instructions/blob/master/dataset_utils/visualize_world_coordinate_system.py) that projects the world coordinate system to the allocentric camera ```22139908```. Results are in [world_coordinate_system_visualizations](https://github.com/leolyliu/TACO-Instructions/tree/master/assets/world_coordinate_system_visualizations). Data sequences from each date share the same world coordinate system. For the date ```20231002```, the world coordinate system is on the table, for other dates, the system is on the ground. The z-axis is always upward, and the system is always right-handed.

**Comment by leolyliu** [comment]
The camera coordinate systems relative to the world coordinate system are defined in the extrinsic files. For allocentric cameras, the extrinsic values are the "R" and "T" in ```calibration.json```. Their usages are in [visualize_world_coordinate_system.py](https://github.com/leolyliu/TACO-Instructions/blob/master/dataset_utils/visualize_world_coordinate_system.py). For the egocentric camera, the extrinsic values are in ```egocentric_frame_extrinsic.npy```. Their usages are in [project_pose_to_egocentric_view.py](https://github.com/leolyliu/TACO-Instructions/blob/master/dataset_utils/project_pose_to_egocentric_view.py).
